receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  cassandra:
    dsn: 127.0.0.1
    keyspace: "otel"
    trace_table: "otel_spans"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ cassandra ]
