receivers:
  otlp:
    protocols:
      http:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

processors:
  deltatocumulative:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [deltatocumulative] 
      exporters: [debug]
