apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
        # # Comment out this block below to get access to system metrics regarding
        # # the OpenTelemetry Collector and its environment, such as spans or metrics
        # # processed, running and sent, queue sizes, uptime, k8s information
        # # and much more.
        #
        # prometheus:
        #   config:
        #     scrape_configs:
        #     - job_name: 'otelcol'
        #       scrape_interval: 10s
        #       static_configs:
        #       - targets: ['0.0.0.0:8888']
        #       metric_relabel_configs:
        #       - source_labels: [ __name__ ]
        #         regex: '.*grpc_io.*'
        #         action: drop
    exporters:
      datadog:
        api:
          key: <YOUR_API_KEY_HERE>
    processors:
      resourcedetection:
        # ensures host.name and other important resource tags 
        # get picked up
        detectors: [system, env, docker]
        timeout: 5s
        override: false
      # adds various tags related to k8s
      k8sattributes:
      batch:
        # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not
        # go over that.
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [resourcedetection, k8sattributes, batch]
          exporters: [datadog]
        traces:
          receivers: [otlp]
          processors: [resourcedetection, k8sattributes, batch]
          exporters: [datadog]
