
receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"
      grpc:
        endpoint: "localhost:4317"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 1s
          static_configs:
            - targets: [ 'localhost:8888' ]

exporters:
  debug:
    verbosity: detailed
  datadog:
    api:
      key: "key"
    tls:
      insecure_skip_verify: true
    host_metadata:
      enabled: false
    metrics:
      endpoint: ${env:SERVER_URL}

service:
  telemetry:
    metrics:
      level: basic
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [datadog, debug]
    metrics:
      receivers: [prometheus]
      exporters: [datadog, debug]