version: 2

commands:
  attach_to_workspace:
    steps:
      - attach_workspace:
          at: ~/

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - publish-stable:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9].[0-9].[0-9]+.*/
      - publish-dev:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run:
          name: Install bazzar
          command: sudo apt update && sudo apt-get install bzr -y
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - cimg-go-pkg-mod-{{ checksum "go.sum" }}-v2
      - run:
          name: Install tools
          command: make install-tools
      - run:
          name: create modules dir
          command: mkdir -p /home/circleci/go/pkg/mod
      - run:
          name: Verify
          command: make ci
      - run:
          name: Build collector 
          command: make otelcontribcol
      - save_cache:
          key: cimg-go-pkg-mod-{{ checksum "go.sum" }}-v2
          paths:
            - "/home/circleci/go/pkg/mod"
      - store_artifacts:
          path: testbed/tests/results
      - store_test_results:
          path: testbed/tests/results/junit
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish-stable:
    docker:
      - image: cimg/go:1.14
    steps:
      - attach_to_workspace
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            make docker-otelcontribcol
            docker tag otelcontribcol:latest otel/opentelemetry-collector-contrib:${CIRCLE_TAG:1}
            docker tag otelcontribcol:latest otel/opentelemetry-collector-contrib:latest
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push image
          command: |
            docker push otel/opentelemetry-collector-contrib:${CIRCLE_TAG:1}
            docker push otel/opentelemetry-collector-contrib:latest
      - run:
          name: Calculate checksums 
          command: shasum -a 256 bin/* > bin/checksums.txt
      - run:
          name: Create Github release and upload artifacts
          command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_TAG bin/

  publish-dev:
    docker:
      - image: circleci/golang:1.14

    steps:
      - attach_to_workspace
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            make docker-otelcontribcol
            docker tag otelcontribcol:latest otel/opentelemetry-collector-contrib-dev:${CIRCLE_SHA1}
            docker tag otelcontribcol:latest otel/opentelemetry-collector-contrib-dev:latest
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Push image
          command: |
            docker push otel/opentelemetry-collector-contrib-dev:${CIRCLE_SHA1}
            docker push otel/opentelemetry-collector-contrib-dev:latest
