# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: deprecation

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: datadogexporter

# A brief description of the change
note: Deprecate `config` package in favor of structs on the `datadogexporter` package.

# One or more tracking issues related to the change
issues: [8373]
