# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: bug_fix 

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: prometheusexporter

# A brief description of the change
note: Expose the same metric from different targets correctly

# One or more tracking issues related to the change
issues: [ 4986 ]

