# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: breaking

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: prometheusremotewrite

# A brief description of the change
note: Fix Prometheus metric conversion issue where sum metric types do not have `_total` suffix

# One or more tracking issues related to the change
issues: [ 11838 ]
