receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8890']
            - targets: ['localhost:8889']
            - targets: ['localhost:8888']

exporters:
  signalfx:
    access_token: <replace_with_actual_access_token>
    realm: us1
    timeout: 5s

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [signalfx]
