receivers:
  examplereceiver:

processors:
  exampleprocessor:

exporters:
  datadog:
    ## @param hostname - string - optional
    ## A custom hostname.
    ## If unset this will be determined automatically if possible.
    #
    # hostname: customhostname

    ## @param env - string - optional
    ## The environment for unified service tagging.
    ## If unset it will be determined from the `DD_ENV` environment variable.
    #
    # env: prod

    ## @param service - string - optional
    ## The service for unified service tagging.
    ## If unset it will be determined from the `DD_SERVICE` environment variable.
    #
    # service: myservice

    ## @param version - string - optional
    ## The version for unified service tagging.
    ## If unset it will be determined from the `DD_VERSION` environment variable.
    #
    # version: myversion

    ## @param tags - list of strings - optional - default: []
    ## The list of default tags to add to every metric or trace.
    #
    # tags: []

    ## @param metrics - custom object - optional
    ## Metric exporter specific configuration.
    #
    # metrics:
      ## @param namespace - string - optional
      ## The namespace with which to prefix all metrics.
      ## By default metrics are not namespaced.
      #
      # namespace: ""

      ## @param report_percentiles - boolean - optional - default: true
      ## Whether to report percentiles (including minimum and maximum)
      ## for summary metric types.
      ## Disable this to reduce the number of custom metrics.
      #
      # report_percentiles: true

      ## @param report_buckets - boolean - optional - default: false
      ## Whether to report bucket counts for distribution metric types.
      ## Enabling this will increase the number of custom metrics.
      #
      # report_buckets: false

      ## @param dogstatsd - custom object - optional
      ## DogStatSD mode specific configuration.
      #
      # dogstatsd:
        ## @param endpoint - string - default: 127.0.0.1:8125
        ## The DogStatsD endpoint. It can be an UDP or UDS endpoint
        #
        # endpoint: 127.0.0.1:8125

        ## @param telemetry - boolean - default: true
        ## Whether to send telemetry metrics about the number of custom metrics sent.
        #
        # telemetry: true
service:
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [exampleprocessor]
      exporters: [datadog]
