extensions:
receivers:
#  otlp:
#    protocols:
#      grpc:
#      http:
  skywalking:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800
      http:
        endpoint: 0.0.0.0:12800
exporters:
  logging:
    loglevel: -1
service:

  pipelines:

    traces:
      receivers: [skywalking]
      processors:
      exporters: [logging]
#    metrics:
#      receivers: [skywalking]
#      processors:
#      exporters: [logging]



  extensions: []