receivers:
  hostmetrics:
    scrapers:
      cpu:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]
  otlp:
    protocols:
      grpc:
  file:
    path: ./bar
    format: proto
    compression: zstd
  file/2:
    path: ./foo
    format: json

exporters:
  logging:
    loglevel: debug
  file:
    path: ./bar
    format: proto
    compression: zstd
  file/2:
    path: ./foo
    format: proto
    compression: zstd
    rotation:
      max_megabytes: 3
      max_days: 0
      localtime: false
      max_backups: 100

processors:
  batch:

service:
  pipelines:
#    traces:
#      receivers: [file]
#      processors: [batch]
#      exporters: [logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging, file]
