receivers:
  hostmetrics:
    scrapers:
      cpu:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]
  otlp:
    protocols:
      grpc:
  file:
    path: ./bar
    format: proto

exporters:
  logging:
    loglevel: debug
  file:
    path: ./bar
    format: proto
  file/2:
    path: ./foo
    format: json

processors:
  batch:

service:
  pipelines:
#    traces:
#      receivers: [file]
#      processors: [batch]
#      exporters: [logging]
    metrics:
      receivers: [file]
      processors: [batch]
      exporters: [logging]
