extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690
        tls:
          cert_file: /etc/otel-collector.crt
          key_file: /etc/otel-collector.key

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":8888"

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check]
