exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awskinesisexporter v0.71.0"
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: "go.opentelemetry.io/collector v0.71.0"

extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/headers_setter v0.71.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.71.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/lumigoauthextension v0.71.0"

receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: "go.opentelemetry.io/collector v0.71.0"
  - import: "go.opentelemetry.io/collector/receiver/k8seventsreceiver v0.71.0"

processors:
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.71.0
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.71.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.71.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.71.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.71.0"

replaces:
  # a list of "replaces" directives that will be part of the resulting go.mod
  - github.com/open-telemetry/opentelemetry-collector-contrib/extension/lumigoauthextension v0.71.0 => github.com/lumigo-io/opentelemetry-collector-contrib/extension/lumigoauthextension
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionbykeyprocessor v0.71.0 => github.com/lumigo-io/opentelemetry-collector-contrib/processor/redactionbykeyprocessor
