apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonapp
  labels:
    jsonapp: jsonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      jsonapp: jsonapp
  template:
    metadata:
      labels:
        jsonapp: jsonapp
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: jsonapp
          image: shivanshu1333/samplejsonlog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      volumes:
        - name: varlog
          hostPath:
            path: /var/log