# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: breaking

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: pkg/stanza, filelog, journald, syslog, tcplog, udplog, windowseventlog, logstransform

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Remove ability to configure `converter`.

# One or more tracking issues related to the change
issues: [15696]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  The design of the converter is opaque and its behavior may change in the future.
  Because of this, the `converter` settings are deemed unstable. The actual behavior of the
  converter remains unchanged, but will always use the former default values.
