# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: instanaexporter

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Added a new configuration option ca_file which takes the certificate authority file for an Instana backend with a self signed certificate

# One or more tracking issues related to the change
issues: [14602]
