# Use this changelog template to create an entry for release notes.
# If your change doesn't affect end users, such as a test fix or a tooling change,
# you should instead start your pull request title with [chore] or use the "Skip Changelog" label.

# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: 'breaking'

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: prometheusreceiver

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: "Add the `trim_metric_suffixes` configuration option to allow enable metric suffix trimming."

# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
issues: [21743, 8950]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: | 
  When enabled, suffixes for unit and type are trimmed from metric names. 
  If you previously enabled the `pkg.translator.prometheus.NormalizeName` 
  feature gate, you will need to enable this option to have suffixes trimmed.
