# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: breaking

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: exporter/routingprocessor

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Rename OTTL `expression` configuration parameter of the routing table to `statement` to align with the OTTL naming.

# One or more tracking issues related to the change
issues: [14950]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext:
