# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: servicegraphprocessor

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Making peer attributes of virtual node building configurable

# One or more tracking issues related to the change
issues: [20428]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  add new config items(virtual_node_peer_attributes: [db.name, rpc.service]) in Config: