# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: exporter/awss3exporter

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Allow custom endpoints to be configured for exporting spans

# One or more tracking issues related to the change
issues: [21833]

