name: build-and-test-windows
on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
env:
  TEST_RESULTS: testbed/tests/results/junit/results.xml

jobs:
  windows-unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: install iis
        run: Install-WindowsFeature -name Web-Server -IncludeManagementTools
      - name: Install Active Directory DS
        run: Install-WindowsFeature -name AD-Domain-Services -IncludeManagementTools
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Cache Go
        uses: actions/cache@v3
        with:
          path: |
            \Users\runneradmin\go\pkg\mod
            %LocalAppData%\go-build
          key: v1-go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - name: Run Unit tests
        # use default Go build tags from Makefile.common
        run: go test --tags containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper ./...
      - name: Run IIS Unit Tests
        run: cd receiver/iisreceiver && go test --tags containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper ./...        
      - name: Run Active Directory DS Unit Tests
        run: |
          ./testdata/scrape-available-counters.ps1
          go test --tags containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper ./...        
        working-directory: ./receiver/activedirectorydsreceiver
      - name: GitHub Issue Generator
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        run: |
          cd internal/tools && go install go.opentelemetry.io/build-tools/issuegenerator
          issuegenerator $TEST_RESULTS
