name: build-and-test-windows
on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
env:
  TEST_RESULTS: testbed/tests/results/junit/results.xml

jobs:
  setup-environment:
    runs-on: windows-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go Mod
        id: go-mod-cache
        uses: actions/cache@v3
        with:
          path: |
            ~\go\pkg\mod
          key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-mod-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
  windows-unittest-matrix:
    needs: [setup-environment]
    strategy:
      matrix:
        group:
          - receiver-0
          - receiver-1
          - processor
          - exporter
          - extension
          - internal
          - other
    runs-on: windows-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - if: matrix.group == 'receiver-0'
        name: install IIS
        run: Install-WindowsFeature -name Web-Server -IncludeManagementTools
      - if: matrix.group == 'receiver-0'
        name: Install Active Directory DS
        run: Install-WindowsFeature -name AD-Domain-Services -IncludeManagementTools
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Cache Go Mod
        id: go-mod-cache
        uses: actions/cache@v3
        with:
          path: |
            ~\go\pkg\mod
          key: go-mod-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-mod-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
      - name: Cache Go Build
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\go-build
          key: go-build-cache-${{ matrix.group }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Run Unit tests
        run: make gotest GROUP=${{ matrix.group }}
  windows-unittest:
    runs-on: windows-latest
    needs: [windows-unittest-matrix]
    steps:
      - name: Unit Tests Complete
        run: echo "Windows unit tests complete"
