name: 'Ping code owners on PRs'
on:
  pull_request:
    types: [labeled]

jobs:
  ping-owners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Run ping-codeowners-prs.sh
        run: ./.github/workflows/scripts/ping-codeowners-prs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
          COMPONENT: ${{ github.event.label.name }}
          SENDER: ${{ github.event.sender.login }}
