name: tracegen
on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  publish-dev:
    runs-on: ubuntu-latest
#    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && github.repository == 'open-telemetry/opentelemetry-collector-contrib'
    permissions:
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tracegen to Github packages
        uses: docker/build-push-action@v2
        with:
          context: tracegen
          push: true
          tags: ghcr.io/open-telemetry/opentelemetry-collector-contrib/tracegen:latest
  publish-stable:
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'open-telemetry/opentelemetry-collector-contrib'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set Release Tag
        id: github_tag
        run: ./.github/workflows/scripts/set_release_tag.sh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tracegen to Github packages
        uses: docker/build-push-action@v2
        with:
          context: tracegen
          push: true
          tags: ghcr.io/open-telemetry/opentelemetry-collector-contrib/tracegen:$RELEASE_TAG
        env:
          RELEASE_TAG: 123
#          RELEASE_TAG: ${{ steps.github_tag.outputs.tag }}
